name: CI-CD

on:
    push:
        branches: [main]

jobs:
    linter:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: '16'
                  cache: 'npm'
            - name: Cache dependencies
            id: cache
            uses: actions/cache@v3
            with:
                path: ./node_modules
                key: modules-${{ hashFiles('package-lock.json') }}
            - name: Install dependencies
            if: steps.cache.outputs.cache-hit != 'true'			
            run: npm ci			
            - name: Run linter			
            run: npm run eslint
			
    build:		
        needs: linter     		
        runs-on: ubuntu-latest		
        steps:
            - uses: actions/checkout@v3
            - name: Build image
            run: docker build -t ${{secrets.DOCKER_HUB_USERNAME}}/devops-nodejs-app:latest .
	
    push:		
        needs: build		
        runs-on: ubuntu-latest		
        steps:
            - uses: actions/checkout@v3
            - name: Login to DockerHub
                uses: docker/login-action@v2
                with:
                  username: ${{ secrets.DOCKER_HUB_USERNAME }}
                  password: ${{ secrets.DOCKER_HUB_PASSWORD }}
            - name: Build and push
                uses: docker/build-push-action@v3
                with:
                  context: .
                  tags: ${{secrets.DOCKER_HUB_USERNAME}}/devops-nodejs-app:latest
                  push: true             
    check-endpoint:		
        needs: push		
        runs-on: ubuntu-latest		
        steps:
            - name: Pull image
            run: docker pull ${{secrets.DOCKER_HUB_USERNAME}}/devops-nodejs-app:latest
            - name: Run image
            run: docker run -p 80:80 -d ${{secrets.DOCKER_HUB_USERNAME}}/devops-nodejs-app
            - name: Check home endpoint
                run: |
                  sleep 5;
                  curl localhost:80/home;